#!/bin/tcsh -f

if (! -d universal) mkdir universal
if (! -d lib) mkdir lib

rm universal/*.a

xcrun -sdk iphoneos lipo -create -arch armv7 armv7/libavcodec.a -arch armv7s armv7s/libavcodec.a -arch i386 i386/libavcodec.a -output universal/libavcodec.a
xcrun -sdk iphoneos lipo -create -arch armv7 armv7/libavdevice.a -arch armv7s armv7s/libavdevice.a -arch i386 i386/libavdevice.a -output universal/libavdevice.a
xcrun -sdk iphoneos lipo -create -arch armv7 armv7/libavformat.a -arch armv7s armv7s/libavformat.a -arch i386 i386/libavformat.a -output universal/libavformat.a
xcrun -sdk iphoneos lipo -create -arch armv7 armv7/libavutil.a -arch armv7s armv7s/libavutil.a -arch i386 i386/libavutil.a -output universal/libavutil.a
xcrun -sdk iphoneos lipo -create -arch armv7 armv7/libswscale.a -arch armv7s armv7s/libswscale.a -arch i386 i386/libswscale.a -output universal/libswscale.a
xcrun -sdk iphoneos lipo -create -arch armv7 armv7/libswresample.a -arch armv7s armv7s/libswresample.a -arch i386 i386/libswresample.a -output universal/libswresample.a
xcrun -sdk iphoneos lipo -create -arch armv7 armv7/libavfilter.a -arch armv7s armv7s/libavfilter.a -arch i386 i386/libavfilter.a -output universal/libavfilter.a

rm lib/*.a

cp universal/*.a lib/
